// /src/lib/visaCountries.ts
// Photo requirements for each country's visa/passport

export type VisaCountry = {
  slug: string;
  name: string;
  flag: string;
  maxKB: number;
  widthPx: number;
  heightPx: number;
  dpi: number;
  background: string;
  notes: string;
  applyUrl?: string;
  searches: string; // monthly search volume estimate
};

export const VISA_COUNTRIES: VisaCountry[] = [
  {
    slug: 'uk-visa',
    name: 'UK Visa',
    flag: '🇬🇧',
    maxKB: 6144, // 6MB but must be under 6MB
    widthPx: 600,
    heightPx: 750,
    dpi: 300,
    background: 'White or light grey',
    notes: 'UK visa photo must be 600×750px, under 6MB. Plain white or light grey background. Face must fill 70-80% of frame.',
    applyUrl: 'https://www.gov.uk/apply-to-come-to-the-uk',
    searches: '90K/mo',
  },
  {
    slug: 'schengen-visa',
    name: 'Schengen Visa',
    flag: '🇪🇺',
    maxKB: 500,
    widthPx: 600,
    heightPx: 800,
    dpi: 300,
    background: 'White',
    notes: 'Schengen visa photo: 35×45mm, white background, taken within last 6 months. For online upload: 600×800px under 500KB.',
    searches: '110K/mo',
  },
  {
    slug: 'canada-visa',
    name: 'Canada Visa',
    flag: '🇨🇦',
    maxKB: 4000,
    widthPx: 420,
    heightPx: 540,
    dpi: 300,
    background: 'White',
    notes: 'Canada eTA/visa photo: 420×540px minimum, white background, under 4MB. Face must be 31-36mm from chin to crown.',
    applyUrl: 'https://www.canada.ca/en/immigration-refugees-citizenship',
    searches: '80K/mo',
  },
  {
    slug: 'australia-visa',
    name: 'Australia Visa',
    flag: '🇦🇺',
    maxKB: 5120,
    widthPx: 600,
    heightPx: 600,
    dpi: 300,
    background: 'White or light grey',
    notes: 'Australian visa photo: 600×600px to 1200×1200px, under 5MB. Head centered, white or light grey background.',
    applyUrl: 'https://immi.homeaffairs.gov.au',
    searches: '70K/mo',
  },
  {
    slug: 'japan-visa',
    name: 'Japan Visa',
    flag: '🇯🇵',
    maxKB: 240,
    widthPx: 600,
    heightPx: 600,
    dpi: 300,
    background: 'White',
    notes: 'Japan visa photo: 45×45mm, white background, plain background. For digital submission under 240KB.',
    searches: '55K/mo',
  },
  {
    slug: 'india-visa',
    name: 'India Visa (e-Visa)',
    flag: '🇮🇳',
    maxKB: 300,
    widthPx: 350,
    heightPx: 350,
    dpi: 300,
    background: 'White',
    notes: 'India e-Visa photo: 350×350px, JPEG only, under 300KB, white background. Face must fill 70-80% of frame.',
    applyUrl: 'https://indianvisaonline.gov.in',
    searches: '95K/mo',
  },
  {
    slug: 'china-visa',
    name: 'China Visa',
    flag: '🇨🇳',
    maxKB: 120,
    widthPx: 354,
    heightPx: 472,
    dpi: 300,
    background: 'White',
    notes: 'China visa photo: 354×472px (33×48mm), JPEG under 120KB, white background, no glasses.',
    searches: '60K/mo',
  },
  {
    slug: 'uae-visa',
    name: 'UAE Visa / Dubai',
    flag: '🇦🇪',
    maxKB: 200,
    widthPx: 600,
    heightPx: 600,
    dpi: 300,
    background: 'White',
    notes: 'UAE visa photo: white background, JPEG, under 200KB, 600×600px. Recent photo within 3 months.',
    searches: '45K/mo',
  },
  {
    slug: 'brazil-visa',
    name: 'Brazil Visa',
    flag: '🇧🇷',
    maxKB: 300,
    widthPx: 600,
    heightPx: 600,
    dpi: 300,
    background: 'White',
    notes: 'Brazil visa photo: 5×5cm, white background, JPEG under 300KB for digital submission.',
    searches: '30K/mo',
  },
  {
    slug: 'russia-visa',
    name: 'Russia Visa',
    flag: '🇷🇺',
    maxKB: 300,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White or light grey',
    notes: 'Russia visa photo: 35×45mm (413×531px at 300dpi), white or light grey background, under 300KB.',
    searches: '25K/mo',
  },
  {
    slug: 'new-zealand-visa',
    name: 'New Zealand Visa',
    flag: '🇳🇿',
    maxKB: 5120,
    widthPx: 900,
    heightPx: 1200,
    dpi: 300,
    background: 'White or light grey',
    notes: 'New Zealand visa: 900×1200px, under 5MB, plain light background.',
    searches: '20K/mo',
  },
  {
    slug: 'south-korea-visa',
    name: 'South Korea Visa',
    flag: '🇰🇷',
    maxKB: 240,
    widthPx: 354,
    heightPx: 472,
    dpi: 300,
    background: 'White',
    notes: 'South Korea visa: 35×45mm (354×472px), white background, JPEG under 240KB.',
    searches: '35K/mo',
  },
  {
    slug: 'turkey-visa',
    name: 'Turkey e-Visa',
    flag: '🇹🇷',
    maxKB: 300,
    widthPx: 600,
    heightPx: 600,
    dpi: 300,
    background: 'White',
    notes: 'Turkey e-Visa: JPEG photo, white background, under 300KB, face must be clear and centered.',
    applyUrl: 'https://www.evisa.gov.tr',
    searches: '50K/mo',
  },
  {
    slug: 'thailand-visa',
    name: 'Thailand Visa',
    flag: '🇹🇭',
    maxKB: 200,
    widthPx: 400,
    heightPx: 514,
    dpi: 300,
    background: 'White',
    notes: 'Thailand visa photo: 4×5cm (400×514px), white background, JPEG under 200KB.',
    searches: '40K/mo',
  },
  {
    slug: 'vietnam-visa',
    name: 'Vietnam e-Visa',
    flag: '🇻🇳',
    maxKB: 300,
    widthPx: 400,
    heightPx: 514,
    dpi: 300,
    background: 'White',
    notes: 'Vietnam e-Visa: 4×5cm, white background, JPEG under 300KB, taken within 6 months.',
    applyUrl: 'https://evisa.xuatnhapcanh.gov.vn',
    searches: '35K/mo',
  },
  {
    slug: 'mexico-visa',
    name: 'Mexico Visa',
    flag: '🇲🇽',
    maxKB: 300,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Mexico visa: 35×45mm, white background, JPEG under 300KB for digital submission.',
    searches: '25K/mo',
  },
  {
    slug: 'singapore-visa',
    name: 'Singapore Visa',
    flag: '🇸🇬',
    maxKB: 2048,
    widthPx: 400,
    heightPx: 514,
    dpi: 300,
    background: 'White',
    notes: 'Singapore visa: 35×45mm (400×514px), white background, JPEG, under 2MB.',
    searches: '30K/mo',
  },
  {
    slug: 'malaysia-visa',
    name: 'Malaysia Visa',
    flag: '🇲🇾',
    maxKB: 300,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Malaysia eNTRI/visa: 35×45mm, white background, JPEG under 300KB.',
    searches: '25K/mo',
  },
  {
    slug: 'germany-visa',
    name: 'Germany Visa',
    flag: '🇩🇪',
    maxKB: 6144,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White or light grey',
    notes: 'German Schengen visa: 35×45mm biometric photo, white or light grey background, under 6MB.',
    searches: '40K/mo',
  },
  {
    slug: 'france-visa',
    name: 'France Visa',
    flag: '🇫🇷',
    maxKB: 6144,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'France Schengen visa: 35×45mm, white background, biometric standard.',
    searches: '35K/mo',
  },
  {
    slug: 'italy-visa',
    name: 'Italy Visa',
    flag: '🇮🇹',
    maxKB: 500,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Italy Schengen visa: 35×45mm, white background, JPEG under 500KB.',
    searches: '30K/mo',
  },
  {
    slug: 'spain-visa',
    name: 'Spain Visa',
    flag: '🇪🇸',
    maxKB: 500,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Spain Schengen visa: 35×45mm biometric photo, white background, under 500KB.',
    searches: '30K/mo',
  },
  {
    slug: 'netherlands-visa',
    name: 'Netherlands Visa',
    flag: '🇳🇱',
    maxKB: 500,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Netherlands Schengen: 35×45mm, white background, JPEG under 500KB.',
    searches: '20K/mo',
  },
  {
    slug: 'egypt-visa',
    name: 'Egypt e-Visa',
    flag: '🇪🇬',
    maxKB: 300,
    widthPx: 400,
    heightPx: 514,
    dpi: 300,
    background: 'White',
    notes: 'Egypt e-Visa: 4×5cm photo, white background, JPEG under 300KB.',
    applyUrl: 'https://visa2egypt.gov.eg',
    searches: '25K/mo',
  },
  {
    slug: 'kenya-visa',
    name: 'Kenya e-Visa',
    flag: '🇰🇪',
    maxKB: 1000,
    widthPx: 400,
    heightPx: 514,
    dpi: 300,
    background: 'White',
    notes: 'Kenya e-Visa: passport photo style, white background, JPEG under 1MB.',
    applyUrl: 'https://evisa.go.ke',
    searches: '15K/mo',
  },
  {
    slug: 'south-africa-visa',
    name: 'South Africa Visa',
    flag: '🇿🇦',
    maxKB: 2048,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White or light grey',
    notes: 'South Africa visa: 35×45mm, white or light grey background, JPEG under 2MB.',
    searches: '20K/mo',
  },
  {
    slug: 'nigeria-visa',
    name: 'Nigeria Visa',
    flag: '🇳🇬',
    maxKB: 200,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Nigeria visa: 35×45mm, white background, JPEG under 200KB, recent photo.',
    searches: '15K/mo',
  },
  {
    slug: 'indonesia-visa',
    name: 'Indonesia Visa',
    flag: '🇮🇩',
    maxKB: 300,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Indonesia visa on arrival/e-VOA: 35×45mm, white background, JPEG under 300KB.',
    searches: '25K/mo',
  },
  {
    slug: 'philippines-visa',
    name: 'Philippines Visa',
    flag: '🇵🇭',
    maxKB: 2048,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Philippines visa: 35×45mm biometric, white background, JPEG under 2MB.',
    searches: '20K/mo',
  },
  {
    slug: 'pakistan-visa',
    name: 'Pakistan Visa',
    flag: '🇵🇰',
    maxKB: 50,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Pakistan e-Visa: photo under 50KB, white background, JPEG format only.',
    applyUrl: 'https://visa.nadra.gov.pk',
    searches: '20K/mo',
  },
  {
    slug: 'bangladesh-visa',
    name: 'Bangladesh Visa',
    flag: '🇧🇩',
    maxKB: 100,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Bangladesh visa: 35×45mm, white background, JPEG under 100KB.',
    searches: '15K/mo',
  },
  {
    slug: 'sri-lanka-visa',
    name: 'Sri Lanka e-Visa',
    flag: '🇱🇰',
    maxKB: 250,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Sri Lanka ETA: white background, JPEG under 250KB, taken within 6 months.',
    applyUrl: 'https://eta.gov.lk',
    searches: '20K/mo',
  },
  {
    slug: 'nepal-visa',
    name: 'Nepal Visa',
    flag: '🇳🇵',
    maxKB: 50,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Nepal tourist visa on arrival: digital photo under 50KB, JPEG, white background.',
    searches: '15K/mo',
  },
  {
    slug: 'portugal-visa',
    name: 'Portugal Visa',
    flag: '🇵🇹',
    maxKB: 500,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Portugal Schengen visa: 35×45mm, white background, biometric standard.',
    searches: '20K/mo',
  },
  {
    slug: 'sweden-visa',
    name: 'Sweden Visa',
    flag: '🇸🇪',
    maxKB: 500,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White or light grey',
    notes: 'Sweden Schengen visa: 35×45mm biometric, light background, JPEG under 500KB.',
    searches: '15K/mo',
  },
  {
    slug: 'poland-visa',
    name: 'Poland Visa',
    flag: '🇵🇱',
    maxKB: 500,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Poland Schengen visa: 35×45mm, white background, biometric photo standard.',
    searches: '15K/mo',
  },
  {
    slug: 'ukraine-visa',
    name: 'Ukraine Visa',
    flag: '🇺🇦',
    maxKB: 300,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Ukraine visa: 35×45mm, white background, JPEG under 300KB.',
    searches: '10K/mo',
  },
  {
    slug: 'switzerland-visa',
    name: 'Switzerland Visa',
    flag: '🇨🇭',
    maxKB: 500,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White or light grey',
    notes: 'Switzerland Schengen visa: 35×45mm biometric, light background.',
    searches: '15K/mo',
  },
  {
    slug: 'saudi-arabia-visa',
    name: 'Saudi Arabia Visa',
    flag: '🇸🇦',
    maxKB: 200,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Saudi Arabia tourist/Umrah visa: white background, JPEG under 200KB.',
    applyUrl: 'https://visa.mofa.gov.sa',
    searches: '30K/mo',
  },
  {
    slug: 'jordan-visa',
    name: 'Jordan Visa',
    flag: '🇯🇴',
    maxKB: 200,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Jordan visa: 35×45mm, white background, JPEG under 200KB.',
    searches: '15K/mo',
  },
  {
    slug: 'iran-visa',
    name: 'Iran Visa',
    flag: '🇮🇷',
    maxKB: 100,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Iran visa on arrival/e-Visa: 35×45mm, white background, JPEG under 100KB.',
    searches: '10K/mo',
  },
  {
    slug: 'ethiopia-visa',
    name: 'Ethiopia e-Visa',
    flag: '🇪🇹',
    maxKB: 200,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Ethiopia e-Visa: passport-style photo, white background, JPEG under 200KB.',
    applyUrl: 'https://www.evisa.gov.et',
    searches: '10K/mo',
  },
  {
    slug: 'morocco-visa',
    name: 'Morocco Visa',
    flag: '🇲🇦',
    maxKB: 300,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Morocco visa: 35×45mm, white background, JPEG under 300KB.',
    searches: '15K/mo',
  },
  {
    slug: 'argentina-visa',
    name: 'Argentina Visa',
    flag: '🇦🇷',
    maxKB: 300,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Argentina visa/SUBE: passport-style, white background, JPEG under 300KB.',
    searches: '15K/mo',
  },
  {
    slug: 'colombia-visa',
    name: 'Colombia Visa',
    flag: '🇨🇴',
    maxKB: 300,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Colombia Migración: passport photo style, white background, JPEG under 300KB.',
    searches: '10K/mo',
  },
  {
    slug: 'peru-visa',
    name: 'Peru Visa',
    flag: '🇵🇪',
    maxKB: 300,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Peru visa: 35×45mm, white background, JPEG under 300KB.',
    searches: '10K/mo',
  },
  {
    slug: 'ghana-visa',
    name: 'Ghana Visa',
    flag: '🇬🇭',
    maxKB: 200,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Ghana visa: passport-style photo, white background, JPEG under 200KB.',
    searches: '10K/mo',
  },
  {
    slug: 'cambodia-visa',
    name: 'Cambodia e-Visa',
    flag: '🇰🇭',
    maxKB: 1024,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Cambodia e-Visa: passport photo, white background, JPEG under 1MB.',
    applyUrl: 'https://www.evisa.gov.kh',
    searches: '15K/mo',
  },
  {
    slug: 'myanmar-visa',
    name: 'Myanmar e-Visa',
    flag: '🇲🇲',
    maxKB: 300,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    background: 'White',
    notes: 'Myanmar e-Visa: 35×45mm, white background, JPEG under 300KB.',
    applyUrl: 'https://evisa.moip.gov.mm',
    searches: '10K/mo',
  },
  { slug: 'afghanistan-visa', name: 'Afghanistan Visa', flag: '?', maxKB: 300, widthPx: 400, heightPx: 500, dpi: 300, background: 'White', notes: 'Afghanistan Visa: white background, under 300KB.', searches: '5K/mo' },
  { slug: 'albania-visa', name: 'Albania Visa', flag: '?', maxKB: 500, widthPx: 413, heightPx: 531, dpi: 300, background: 'White', notes: 'Albania Visa: white background, under 500KB.', searches: '5K/mo' },
  { slug: 'algeria-visa', name: 'Algeria Visa', flag: '?', maxKB: 500, widthPx: 413, heightPx: 531, dpi: 300, background: 'White', notes: 'Algeria Visa: white background, under 500KB.', searches: '5K/mo' },
  { slug: 'austria-visa', name: 'Austria Visa', flag: '?', maxKB: 500, widthPx: 600, heightPx: 800, dpi: 300, background: 'White', notes: 'Austria Visa: white background, under 500KB.', searches: '5K/mo' },
  { slug: 'azerbaijan-visa', name: 'Azerbaijan e-Visa', flag: '?', maxKB: 100, widthPx: 413, heightPx: 531, dpi: 300, background: 'White', notes: 'Azerbaijan e-Visa: white background, under 100KB.', searches: '5K/mo' },
  { slug: 'bahrain-visa', name: 'Bahrain Visa', flag: '?', maxKB: 200, widthPx: 413, heightPx: 531, dpi: 300, background: 'White', notes: 'Bahrain Visa: white background, under 200KB.', searches: '5K/mo' },
  { slug: 'belarus-visa', name: 'Belarus Visa', flag: '?', maxKB: 300, widthPx: 413, heightPx: 531, dpi: 300, background: 'White', notes: 'Belarus Visa: white background, under 300KB.', searches: '5K/mo' },
  { slug: 'belgium-visa', name: 'Belgium Visa', flag: '?', maxKB: 500, widthPx: 600, heightPx: 800, dpi: 300, background: 'White', notes: 'Belgium Visa: white background, under 500KB.', searches: '5K/mo' },
  { slug: 'bolivia-visa', name: 'Bolivia Visa', flag: '?', maxKB: 300, widthPx: 413, heightPx: 531, dpi: 300, background: 'White', notes: 'Bolivia Visa: white background, under 300KB.', searches: '5K/mo' },
  { slug: 'bulgaria-visa', name: 'Bulgaria Visa', flag: '?', maxKB: 500, widthPx: 413, heightPx: 531, dpi: 300, background: 'White', notes: 'Bulgaria Visa: white background, under 500KB.', searches: '5K/mo' },
  { slug: 'cameroon-visa', name: 'Cameroon Visa', flag: '?', maxKB: 300, widthPx: 413, heightPx: 531, dpi: 300, background: 'White', notes: 'Cameroon Visa: white background, under 300KB.', searches: '5K/mo' },
  { slug: 'chile-visa', name: 'Chile Visa', flag: '?', maxKB: 300, widthPx: 413, heightPx: 531, dpi: 300, background: 'White', notes: 'Chile Visa: white background, under 300KB.', searches: '5K/mo' },
  { slug: 'croatia-visa', name: 'Croatia Visa', flag: '?', maxKB: 500, widthPx: 600, heightPx: 800, dpi: 300, background: 'White', notes: 'Croatia Visa: white background, under 500KB.', searches: '5K/mo' },
  { slug: 'cuba-visa', name: 'Cuba Visa', flag: '?', maxKB: 300, widthPx: 413, heightPx: 531, dpi: 300, background: 'White', notes: 'Cuba Visa: white background, under 300KB.', searches: '5K/mo' },
  { slug: 'czech-visa', name: 'Czech Republic Visa', flag: '?', maxKB: 500, widthPx: 600, heightPx: 800, dpi: 300, background: 'White', notes: 'Czech Republic Visa: white background, under 500KB.', searches: '5K/mo' },
  { slug: 'denmark-visa', name: 'Denmark Visa', flag: '?', maxKB: 500, widthPx: 600, heightPx: 800, dpi: 300, background: 'White', notes: 'Denmark Visa: white background, under 500KB.', searches: '5K/mo' },
  { slug: 'ecuador-visa', name: 'Ecuador Visa', flag: '?', maxKB: 300, widthPx: 413, heightPx: 531, dpi: 300, background: 'White', notes: 'Ecuador Visa: white background, under 300KB.', searches: '5K/mo' },
  { slug: 'f1-visa', name: 'F1 Student Visa USA', flag: '?', maxKB: 240, widthPx: 600, heightPx: 600, dpi: 300, background: 'White', notes: 'F1 Student Visa USA: white background, under 240KB.', searches: '5K/mo' },
  { slug: 'finland-visa', name: 'Finland Visa', flag: '?', maxKB: 500, widthPx: 600, heightPx: 800, dpi: 300, background: 'White', notes: 'Finland Visa: white background, under 500KB.', searches: '5K/mo' },
  { slug: 'georgia-visa', name: 'Georgia e-Visa', flag: '?', maxKB: 100, widthPx: 413, heightPx: 531, dpi: 300, background: 'White', notes: 'Georgia e-Visa: white background, under 100KB.', searches: '5K/mo' },
  { slug: 'greece-visa', name: 'Greece Visa', flag: '?', maxKB: 500, widthPx: 600, heightPx: 800, dpi: 300, background: 'White', notes: 'Greece Visa: white background, under 500KB.', searches: '5K/mo' },
  { slug: 'hungary-visa', name: 'Hungary Visa', flag: '?', maxKB: 500, widthPx: 600, heightPx: 800, dpi: 300, background: 'White', notes: 'Hungary Visa: white background, under 500KB.', searches: '5K/mo' },
  { slug: 'iraq-visa', name: 'Iraq Visa', flag: '?', maxKB: 300, widthPx: 413, heightPx: 531, dpi: 300, background: 'White', notes: 'Iraq Visa: white background, under 300KB.', searches: '5K/mo' },
  { slug: 'ireland-visa', name: 'Ireland Visa', flag: '?', maxKB: 500, widthPx: 413, heightPx: 531, dpi: 300, background: 'White', notes: 'Ireland Visa: white background, under 500KB.', searches: '5K/mo' },
  { slug: 'israel-visa', name: 'Israel Visa', flag: '?', maxKB: 500, widthPx: 413, heightPx: 531, dpi: 300, background: 'White', notes: 'Israel Visa: white background, under 500KB.', searches: '5K/mo' },
  { slug: 'kazakhstan-visa', name: 'Kazakhstan e-Visa', flag: '?', maxKB: 200, widthPx: 413, heightPx: 531, dpi: 300, background: 'White', notes: 'Kazakhstan e-Visa: white background, under 200KB.', searches: '5K/mo' },
  { slug: 'norway-visa', name: 'Norway Visa', flag: '?', maxKB: 500, widthPx: 600, heightPx: 800, dpi: 300, background: 'White', notes: 'Norway Visa: white background, under 500KB.', searches: '5K/mo' },
  { slug: 'senegal-visa', name: 'Senegal Visa', flag: '?', maxKB: 300, widthPx: 413, heightPx: 531, dpi: 300, background: 'White', notes: 'Senegal Visa: white background, under 300KB.', searches: '5K/mo' },
];

export const VISA_SLUG_MAP: Record<string, VisaCountry> = Object.fromEntries(
  VISA_COUNTRIES.map(c => [c.slug, c])
);
