import { withSentryConfig } from "@sentry/nextjs";
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  poweredByHeader: false,

  compress: true,
  modularizeImports: {
    'lucide-react': {
      transform: 'lucide-react/dist/esm/icons/{{member}}',
    },
  },
  images: {
    formats: ['image/avif', 'image/webp'],
    minimumCacheTTL: 31536000,
  },
  productionBrowserSourceMaps: false,
  experimental: {
    optimizePackageImports: ["react", "react-dom", "lucide-react", "@radix-ui/react-icons"],
    optimizeCss: false,
  },
  compiler: {
    removeConsole: process.env.NODE_ENV === "production",
  },
  async redirects() {
    return [
      { source: '/:path*', has: [{ type: 'host', value: 'compressto20kb.com' }], destination: 'https://www.compressto20kb.com/:path*', permanent: true },
      { source: '/compress-for-albania-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-algeria-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-argentina-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-australia-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-austria-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-azerbaijan-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-bahrain-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-bangladesh-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-belarus-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-belgium-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-bolivia-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-bulgaria-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-cambodia-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-cameroon-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-canada-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-chile-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-china-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-colombia-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-croatia-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-cuba-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-czech-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-denmark-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-ecuador-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-finland-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-france-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-georgia-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-germany-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-greece-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-hungary-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-india-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-indonesia-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-iraq-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-ireland-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-israel-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-italy-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-japan-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-jordan-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-kazakhstan-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-kenya-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-malaysia-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-mexico-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-morocco-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-myanmar-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-nepal-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-netherlands-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-nigeria-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-norway-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-peru-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-philippines-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-russia-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-saudi-arabia-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-schengen-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-senegal-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-singapore-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-south-africa-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-south-korea-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-spain-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-sri-lanka-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-sweden-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-switzerland-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-uae-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-uk-visa', destination: '/visa-photo-compressor', permanent: true },
      { source: '/compress-for-vietnam-visa', destination: '/visa-photo-compressor', permanent: true },
    ];
  },
  headers: async () => [
    {
      source: "/(.*)",
      headers: [
        { key: "X-Frame-Options", value: "DENY" },
        { key: "X-Content-Type-Options", value: "nosniff" },
        { key: "X-XSS-Protection", value: "1; mode=block" },
        { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
        { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=(), interest-cohort=()" },
        {
          key: "Content-Security-Policy",
          value: [
            "default-src 'self'",
            "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://challenges.cloudflare.com https://www.googletagmanager.com https://www.google-analytics.com blob:",
            "style-src 'self' 'unsafe-inline'",
            "img-src 'self' data: blob: https://www.googletagmanager.com https://www.google-analytics.com https://stats.g.doubleclick.net",
            "connect-src 'self' https://*.upstash.io https://sentry.io https://*.workers.dev https://www.google-analytics.com https://analytics.google.com https://stats.g.doubleclick.net",
            "frame-src https://challenges.cloudflare.com",
            "worker-src blob: 'self'",
            "object-src 'none'",
            "base-uri 'self'",
          ].join("; "),
        },
      ],
    },
    {
      source: "/_next/static/(.*)",
      headers: [
        { key: "Cache-Control", value: "public, max-age=31536000, immutable" },
      ],
    },
  ],
};

export default withSentryConfig(nextConfig, {
  bundleSizeOptimizations: {
    excludeDebugStatements: true,
    excludeReplayShadowDom: true,
    excludeReplayWorker: true,
  },
  org: "compressto20kb",
  project: "javascript-nextjs",
  silent: !process.env.CI,
  widenClientFileUpload: true,
  tunnelRoute: "/monitoring",
  automaticVercelMonitors: true,
});
