import AuthorBox from '@/app/components/AuthorBox'

const faqSchema = {"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"What are US passport photo requirements?","acceptedAnswer":{"@type":"Answer","text":"US passport photos must be: 2x2 inches (51x51mm), JPEG under 240KB for online applications, white background, taken within 6 months, no glasses, neutral expression, full face visible, eyes open. Print size: 600x600px minimum."}},{"@type":"Question","name":"What file size is required for a US passport photo online?","acceptedAnswer":{"@type":"Answer","text":"For the online US passport renewal application, photos must be JPEG under 240KB and at least 600x600px. Use our tool to compress your passport photo to exactly 200KB JPEG while maintaining the required resolution."}},{"@type":"Question","name":"Can I use an iPhone photo for a US passport?","acceptedAnswer":{"@type":"Answer","text":"Yes, if it meets requirements. iPhone photos are typically 3-5MB — compress to under 240KB JPEG using our tool. Ensure white background, proper lighting, and no glasses. The State Department also has a free photo check tool."}}]};
import type { Metadata } from 'next';
import ClientPage from './client';
export const metadata: Metadata = {
  title: 'US Passport Photo Requirements 2026 — Size, Format & Compression',
  description: 'Official US passport photo requirements for 2026. Size, format, background, and how to compress your photo to under 240KB for online passport renewal.',
  keywords: 'us passport photo requirements, passport photo size, passport photo compression, compress passport photo, us passport online photo',
  alternates: { canonical: 'https://www.compressto20kb.com/blog/us-passport-photo-requirements' },
  openGraph: { url: 'https://www.compressto20kb.com/blog/us-passport-photo-requirements' },
};
export default function Page() { return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: '{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://www.compressto20kb.com"},{"@type":"ListItem","position":2,"name":"Blog","item":"https://www.compressto20kb.com/blog"},{"@type":"ListItem","position":3,"name":"US Passport Photo Requirements 2026","item":"https://www.compressto20kb.com/blog/us-passport-photo-requirements"}]}' }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: '{"@context":"https://schema.org","@type":"BlogPosting","headline":"US Passport Photo Requirements 2026","description":"Official US passport photo requirements for 2026. Size, format, background, and how to compress your photo to under 240KB for online passport renewal.","url":"https://www.compressto20kb.com/blog/us-passport-photo-requirements","datePublished":"2026-01-01","dateModified":"2026-05-12","author":{"@type":"Person","name":"Ethan Blake"},"publisher":{"@type":"Organization","name":"CompressTo20KB","url":"https://www.compressto20kb.com"},"reviewedBy":{"@type":"Person","name":"Ethan Blake"}}' }} /><ClientPage /><AuthorBox /></>; }
